### PR TITLE
Add "[BOM]" (byte-order-mark) text in file encoding info

### PR DESCRIPTION
**Pull request by pachi-belero**
Like in vim-airline
See https://github.com/vim-airline/vim-airline/pull/992 and https://github.com/vim-airline/vim-airline/commit/fdb74f549df6972185daf1fa22fe3647e092b71a

Ref #2015

### CODE REVIEW

**Comment by pachi-belero** [comment]
Closing the pull request due to failing tests, don't know how to fix it

**Comment by PH111P** [comment]
I'm reopening this, as most of the test failures are unrelated.

**Comment by PH111P** [comment]
Configuration-wise, I think it would be better to have a separate segment just for the [BOM] information; this should be an easy modification though.

**Comment by PH111P** [comment]
Replaced by #2030.

**Pull request closed without merging**
