### PR TITLE
support vertically-aligned multi-monitor setups in lemonbar

### PR DESCRIPTION
**Pull request by s-ol**
See #1819

### CODE REVIEW

**Comment by s-ol** [comment]
I didn't write the failing test for this (https://github.com/powerline/powerline/blob/develop/tests/test_bar/test.sh#L172), but I guess it just needs an addition of +0 there for the added y coordinate?

**Comment by PH111P** [comment]
Would you mind fixing the test nevertheless? (This would simplify things a little bit, I suppose)

**Comment by s-ol** [comment]
@PH111P I would but my dev environment is shot at the moment.

**Comment by s-ol** [comment]
thank you for taking care of it @PH111P! Looks like that is a false negative? 

```
Fails and skips summary:
F /root/python|segments :: Failed test(s) from /home/travis/build/powerline/powerline/tests/test_python/test_segments.py
F /root|/home/travis/build/powerline/powerline/tests/test_python/test.sh :: Failed /home/travis/build/powerline/powerline/tests/test_python/test.sh
AF /root/shell|ipython:test :: Failed checking ipython -mIPython
Suite /root failed, summary:
F /root|/home/travis/build/powerline/powerline/tests/test_python/test.sh :: Failed /home/travis/build/powerline/powerline/tests/test_python/test.sh
cache.2
store build cache
```

**Comment by PH111P** [comment]
I think so, too. At least they're totally unrelated. I would consider ignoring the failing tests for now and merge this PR.

**Pull request merged**
