### PR TITLE
Addressing #2027 gradually - use command -v

### PR DESCRIPTION
**Pull request by BlitzKraft**
Currently only changed tests/test.sh and tests/test_bar/test.sh .

Need to check how travis handles this.

### CODE REVIEW

**Comment by BlitzKraft** [comment]
@PH111P Could you help me make sense of the travis log? I don't fully get which test(s) failed or why.

**Comment by PH111P** [comment]
For `rc`, it seems that no powerline output is generated at all and this error pops up:
```
/home/travis/build/powerline/powerline/tests/tmp/shell//path/rc: bad option: --
dpkg-query: package 'rc' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```

For `pdb`, things seem to work better; although there are some random newlines in the output.

**Comment by BlitzKraft** [comment]
Thank you. I'll try and fix the tests, at least for `rc`.

**Comment by BlitzKraft** [comment]
`which` is no longer needed for install and usage, but needed for testing. I am considering this resolved and have it merged. I am open for input/suggestions.

**Comment by PH111P** [comment]
Sounds and looks good.

**Pull request merged**
