### PR TITLE
Add 'output' option to segments.i3wm.workspaces

### PR DESCRIPTION
**Pull request by S0lll0s**
moved out of #1431

### CODE REVIEW

**Comment by ZyX-I** [comment]
Tests are missing.

**Comment by S0lll0s** [comment]
enough tests? pypy & pypy3 are passing.alright, both

**Comment by ZyX-I** [comment]
I have pushed temporary fix for zsh problem. Can you squash, rebase and fix style in tests (linter does not allow more then one space after a comma).

**Comment by S0lll0s** [comment]
better?

**Comment by S0lll0s** [comment]
ah, I guess whatever you changed did work for me aswell; all green.

**Comment by S0lll0s** [comment]
@ZyX-I I made another change, is there a way to reuse this PR or should I resubmit a new one?

**Comment by ZyX-I** [comment]
@S0lll0s No, you can’t reuse a merged PR.

**Pull request merged**
