### PR TITLE
Adding elapsed time to dbus players

### PR DESCRIPTION
**Pull request by chester755**
I have added the dbus elapsed line for all dbus players.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Commit message should reflect the change you made: you did not update Dbus, it is a different project. Line in the PR message is more descriptive (though not in line with the style guide).

**Comment by chester755** [comment]
Thanks for helping me correct the pulling request title. The version of Clementine player I am running is 1.2.3, which was released on Apr 23, 2014. It works with latest 1.3.1 version of Clementine player.

**Comment by ZyX-I** [comment]
@chester755 Commit message, not pull request title. You need to `git commit --amend` and force-push.

**Comment by ZyX-I** [comment]
There actually are no guidelines for PR titles or messages I know about. For commits you need something like “Add elapsed time to Dbus players”. *Not* “Dbus Clementine players”, you do not limit this change to anything.

**Comment by ZyX-I** [comment]
\* Note: ignore test failures for now, needs #1812.

**Comment by ZyX-I** [comment]
And I think it is good idea to remove your new line from where it is located now and write

```
try:
  elapsed = iface.Get(iface_player, 'Position')
except dbus.exceptions.DBusException:
  pl.warning('Missing player elapsed time')
  elapsed = None
else:
  elapsed = _convert_seconds(elapsed / 1e6)

…

  'elapsed': elapsed
```

**Comment by chester755** [comment]
I think I have updated the commit message.

**Comment by chester755** [comment]
That's a very good throught! On it.

**Comment by ZyX-I** [comment]
This variant should not break in case some players do not support “Position”, but should yet give warnings. Based on assumption that elapsed time is not supported because of some players not supporting “Position”, not because whoever initially implemented dbus players support (not me, I am using no specialized music players) overlooked something in documentation.

**Comment by chester755** [comment]
That make sense. I am not sure why the job failed. I tested it locally.

**Comment by ZyX-I** [comment]
@chester755 Player segments are not tested because I have no idea whether I can actually run any of them on travis. Tests fail because bot-ci job was moved to trusty and this repository was not, so finishing #1812 is required to have them in sync again.

**Comment by chester755** [comment]
Oh I see. Thanks anyway for your help.

**Pull request merged**
