### PR TITLE
Fix #1953

### LINKED ISSUE #1953: powerline-status crashes with ipython>=7.0.0
The Powerline plugin for IPython causes it to crash on startup for versions 7.0.0 and 7.0.1; it works well for IPython version 6.5.0.  I will attach the detailed crash report as a comment.  Below is my IPython configuration:

```python
# Enable the Powerline prompt
from powerline.bindings.ipython.since_5 import PowerlinePrompts
c.TerminalInteractiveShell.simple_prompt = False
c.TerminalInteractiveShell.prompts_class = PowerlinePrompts

## Shortcut style to use at the prompt. 'vi' or 'emacs'.
c.TerminalInteractiveShell.editing_mode = 'vi'

## Set the editor used by IPython (default to $EDITOR/vi/notepad).
c.TerminalInteractiveShell.editor = 'vim'

c.TerminalInteractiveShell.highlighting_style = 'monokai'
```

### PR DESCRIPTION
**Pull request by PH111P**
Fixes #1953 by implementing a new renderer.
(I'm sorry for the noise generated by removing trailing white spaces)

### CODE REVIEW

**Comment by BlitzKraft** [comment]
@naftulikay Temporarily, you can clone @PH111P 's fork and run/install and test powerline, and report any further issues. 

@PH111P we can do a squash merge, to reduce the noise in the master. But before that, the tests need to pass. The tests are failing on python3.6 - log is here: https://travis-ci.org/powerline/powerline/jobs/588409040

**Comment by PH111P** [comment]
> @naftulikay Temporarily, you can clone @PH111P 's fork and run/install and test powerline, and report any further issues.
> 
> @PH111P we can do a squash merge, to reduce the noise in the master. But before that, the tests need to pass. The tests are failing on python3.6 - log is here: https://travis-ci.org/powerline/powerline/jobs/588409040

Actually, I'm currently working on fixing the tests, although the failing ones seem to be unrelated.

**Comment by PH111P** [comment]
Indeed, while the ipython tests fail, until now their failure was simply ignored. Further, the ipython tests seemed to assume an archaic version of ipython (< 5.0). Having updated the config for ipython for the test, now they seem to fail because
* ipython with `autocall = 1` produces more output
* something strange happens in the background (?): prompt_toolkit throws some Exception

(Note that, while travis thinks the test passed, it actually didn't as the result of the ipython test is still ignored)

**Comment by PH111P** [comment]
This seems to be a `pexpect` related bug in `prompt_toolkit`: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/886; which should be fixed in the current version of `prompt_toolkit`. As I don't know if/when this version will be available in our testing environment, I'd consider ignoring the ipython tests for now (as we did up until now anyways) and finally merge this PR.

**Comment by BlitzKraft** [comment]
@PH111P : Seconded. Let's merge this.

**Pull request merged**
